# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/usart/usart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart || ORIG_REF_NAME==usart}]

# IP: bd/usart/ip/usart_clk_wiz_0_0/usart_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_clk_wiz_0_0 || ORIG_REF_NAME==usart_clk_wiz_0_0}]

# IP: bd/usart/ip/usart_mig_7series_0_0/usart_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_mig_7series_0_0 || ORIG_REF_NAME==usart_mig_7series_0_0}]

# IP: bd/usart/ip/usart_microblaze_0_0/usart_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_microblaze_0_0 || ORIG_REF_NAME==usart_microblaze_0_0}]

# IP: bd/usart/ip/usart_mdm_1_0/usart_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_mdm_1_0 || ORIG_REF_NAME==usart_mdm_1_0}]

# IP: bd/usart/ip/usart_rst_mig_7series_0_83M_0/usart_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==usart_rst_mig_7series_0_83M_0}]

# IP: bd/usart/ip/usart_axi_uartlite_0_0/usart_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_axi_uartlite_0_0 || ORIG_REF_NAME==usart_axi_uartlite_0_0}]

# IP: bd/usart/ip/usart_axi_smc_0/usart_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_axi_smc_0 || ORIG_REF_NAME==usart_axi_smc_0}]

# IP: bd/usart/ip/usart_microblaze_0_axi_periph_0/usart_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_microblaze_0_axi_periph_0 || ORIG_REF_NAME==usart_microblaze_0_axi_periph_0}]

# IP: bd/usart/ip/usart_dlmb_v10_0/usart_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_dlmb_v10_0 || ORIG_REF_NAME==usart_dlmb_v10_0}]

# IP: bd/usart/ip/usart_ilmb_v10_0/usart_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_ilmb_v10_0 || ORIG_REF_NAME==usart_ilmb_v10_0}]

# IP: bd/usart/ip/usart_dlmb_bram_if_cntlr_0/usart_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==usart_dlmb_bram_if_cntlr_0}]

# IP: bd/usart/ip/usart_ilmb_bram_if_cntlr_0/usart_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==usart_ilmb_bram_if_cntlr_0}]

# IP: bd/usart/ip/usart_lmb_bram_0/usart_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==usart_lmb_bram_0 || ORIG_REF_NAME==usart_lmb_bram_0}]

# XDC: bd/usart/usart_ooc.xdc
