# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/makerspace/makerspace_hd/VivadoProjects/helloworld/helloworld.srcs/sources_1/bd/usart/ip/usart_lmb_bram_0/usart_lmb_bram_0.xci
# IP: The module: 'usart_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/makerspace/makerspace_hd/VivadoProjects/helloworld/helloworld.srcs/sources_1/bd/usart/ip/usart_lmb_bram_0/usart_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'usart_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /media/makerspace/makerspace_hd/VivadoProjects/helloworld/helloworld.srcs/sources_1/bd/usart/ip/usart_lmb_bram_0/usart_lmb_bram_0.xci
# IP: The module: 'usart_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/makerspace/makerspace_hd/VivadoProjects/helloworld/helloworld.srcs/sources_1/bd/usart/ip/usart_lmb_bram_0/usart_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'usart_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
