# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/makerspace/makerspace_hd/VivadoProjects/combinational_circuit/combinational_circuit.cache/wt [current_project]
set_property parent.project_path /media/makerspace/makerspace_hd/VivadoProjects/combinational_circuit/combinational_circuit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty:part0:1.1 [current_project]
set_property ip_output_repo /media/makerspace/makerspace_hd/VivadoProjects/combinational_circuit/combinational_circuit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /media/makerspace/makerspace_hd/VivadoProjects/combinational_circuit/combinational_circuit.srcs/sources_1/new/comb.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/makerspace/makerspace_hd/VivadoProjects/combinational_circuit/combinational_circuit.srcs/constrs_1/new/and_not.xdc
set_property used_in_implementation false [get_files /media/makerspace/makerspace_hd/VivadoProjects/combinational_circuit/combinational_circuit.srcs/constrs_1/new/and_not.xdc]


synth_design -top comb -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef comb.dcp

catch { report_utilization -file comb_utilization_synth.rpt -pb comb_utilization_synth.pb }
