set_property PACKAGE_PIN A8 [get_ports a]
set_property PACKAGE_PIN C11 [get_ports b]
set_property PACKAGE_PIN C10 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property PACKAGE_PIN E1 [get_ports j]
set_property PACKAGE_PIN G4 [get_ports k]
set_property IOSTANDARD LVCMOS33 [get_ports k]
set_property IOSTANDARD LVCMOS33 [get_ports j]

